# The coverage jobs for cpp code
#
# This sperate job exists because C/CPP coverage require build type to be Debug.
# Other coverage jobs e.g java/scala's coverage lives alongside with their test jobs.

name: coverage

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'demo/**'
      - 'docker/**'
      - 'image/**'
      - 'release/**'
      - 'tools/**'
      - '*.md'
      - 'benchmark/**'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'demo/**'
      - 'docker/**'
      - 'image/**'
      - 'release/**'
      - 'tools/**'
      - '*.md'
      - 'benchmark/**'
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-20.04
    env:
      CTEST_PARALLEL_LEVEL: 1 # parallel test level for ctest (make test)
      CMAKE_BUILD_TYPE: Debug
      TESTING_ENABLE: ON
      SQL_PYSDK_ENABLE: OFF
      SQL_JAVASDK_ENABLE: OFF
      NPROC: 2
      BUILD_SHARED_LIBS: ON
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: download lcov
        uses: actions/checkout@v3
        with:
          repository: linux-test-project/lcov
          ref: v1.16
          path: lcov

      - name: install lcov
        working-directory: lcov
        run: |
          sudo make install

      - name: coverage configure
        run: |
          make coverage-configure

      - name: start service
        run: |
          ./steps/ut_zookeeper.sh start
      # make coverage-cpp will gen 16G build/ (no run), run test will take 2G more, so split make and test
      - name: Coverage CPP
        run: |
          cd build
          make -j2
          # rm some irrelevant files
          find . -name "*.o" -type f -delete
          find . -name "*.a" -type f -delete
          find . -type d -name "*.dir" -exec rm -r {} +
          # total 119(120-api_server_test)
          ctest --force-new-ctest-process --output-on-failure -E "api_server_test"

      - name: debug
        if: always()
        run: | 
          du -d 1 -h build
          df

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v3
        with:
          files: build/coverage.info
          name: coverage-cpp
          fail_ci_if_error: true
          verbose: true

      - name: stop service
        run: |
          ./steps/ut_zookeeper.sh stop
