# OpenMLDB build on other os, only trigger by dispatch event and only upload artifacts, not release.
# You should download artifacts manually. And we won't do test in this workflow.
name: other os build

on:
  workflow_dispatch:
    inputs:
      OS:
        description: 'os name: centos6, macos11'
        required: true
        default: 'centos6'

env:
  GIT_SUBMODULE_STRATEGY: recursive
  NPROC: 2 # default Parallel build number for GitHub's Linux runner
  EXAMPLES_ENABLE: OFF # turn off hybridse's example code
  HYBRIDSE_TESTING_ENABLE: OFF # turn off hybridse's test code

jobs:
  centos6: # glibc version is 2.12, glibcxx version is 3.4.13
    if: ${{ github.event.inputs.OS == 'centos6' }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/4paradigm/centos6_gcc7_hybridsql
    env:
      OS: linux
      SQL_PYSDK_ENABLE: OFF
      TESTING_ENABLE: ON
      NPROC: 8
      CTEST_PARALLEL_LEVEL: 1 # parallel test level for ctest (make test)
    steps:
      - uses: actions/checkout@v2

      - name: setup tools
        run: |
          bash steps/centos6_build.sh
          # env setup
          source /opt/rh/devtoolset-8/enable
          export PATH=$PATH:`pwd`

      - name: prepare release
        run: |
          VERSION="snapshot"
          if [[ ${{ github.ref }} == "refs/tags/v"* ]]; then
            VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
            VERSION=${VERSION#v}
            bash steps/prepare_release.sh "$VERSION"
          fi
          echo "OPENMLDB_PREFIX=openmldb-$VERSION-linux" >> $GITHUB_ENV

      - name: enable java on release
        run: |
          echo "SQL_JAVASDK_ENABLE=ON" >> $GITHUB_ENV

      - name: configure
        env:
          SQL_JAVASDK_ENABLE: ${{ env.SQL_JAVASDK_ENABLE }}
        run: |
          make configure CMAKE_INSTALL_PREFIX=${{ env.OPENMLDB_PREFIX }}

      - name: build
        run: |
          make BUILD_BUNDLED=ON
          # GitHub runner disk space is limited
          # delete thirdparty build directory($ROOT/.deps/) to save disk space
          # make thirdpartybuild-clean

      - name: install
        if: ${{ github.event_name == 'push' }}
        run: |
          make install

      - name: package
        if: ${{ github.event_name == 'push' }}
        run: |
          tar czf ${{ env.OPENMLDB_PREFIX }}.tar.gz ${{ env.OPENMLDB_PREFIX }}/

      - name: upload artifacts
        if: ${{ github.event_name == 'push' }}
        uses: actions/upload-artifact@v2
        with:
          path: openmldb-*.tar.gz
          name: release-artifacts

  macos-11:
    if: ${{ github.event.inputs.OS == 'macos11' }}
    runs-on: macos-11
    env:
      OS: darwin
      ARCH: x86_64
      NPROC: 3
      CTEST_PARALLEL_LEVEL: 1 # parallel test level for ctest (make test)
    steps:
      - uses: actions/checkout@v3

      - name: prepare release
        run: |
          VERSION="snapshot"
          if [[ ${{ github.ref }} == "refs/tags/v"* ]]; then
            VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
            VERSION=${VERSION#v}
            bash steps/prepare_release.sh "$VERSION"
          fi
          echo "OPENMLDB_PREFIX=openmldb-$VERSION-darwin" >> $GITHUB_ENV

      - name: enable java on release
        run: |
          echo "SQL_JAVASDK_ENABLE=ON" >> $GITHUB_ENV

      - name: configure
        env:
          SQL_JAVASDK_ENABLE: ${{ env.SQL_JAVASDK_ENABLE }}
        run: |
          make configure CMAKE_INSTALL_PREFIX=${{ env.OPENMLDB_PREFIX }}

      - name: build
        run: |
          make build
          # GitHub runner disk space is limited
          # delete thirdparty build directory($ROOT/.deps/) to save disk space
          # make thirdpartybuild-clean

      - name: install
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
        run: |
          make install

      - name: package
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
        run: |
          tar czf ${{ env.OPENMLDB_PREFIX }}.tar.gz ${{ env.OPENMLDB_PREFIX }}/

      - name: upload artifacts
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
        uses: actions/upload-artifact@v3
        with:
          path: openmldb-*.tar.gz
          name: release-artifacts
# TODO macos 10