# This workflow scp the specified version release files to the match of mirror site
name: Release Mirror

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'release version'
        required: false

jobs:
  cp:
    runs-on: ubuntu-latest
    steps:
      # ssh actions have limitations, so we use raw ssh
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.STAGING_SSH_USER }}
          SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
          SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}
      - name: test
        run: |
          ssh staging 'exit 10'
          echo $?
            