# This workflow runs SDK related jobs for OpenMLDB
name: SDK

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "demo/**"
      - "docker/**"
      - "image/**"
      - "release/**"
      - "tools/**"
      - "*.md"
    tags:
      - v*
  pull_request:
    paths-ignore:
      - "docs/**"
      - "demo/**"
      - "docker/**"
      - "image/**"
      - "release/**"
      - "tools/**"
      - "*.md"
  workflow_dispatch:

env:
  GIT_SUBMODULE_STRATEGY: recursive
  NPROC: 2 # default Parallel build number for GitHub's Linux runner
  EXAMPLES_ENABLE: OFF # turn off hybridse's example code
  HYBRIDSE_TESTING_ENABLE: OFF # turn off hybridse's test code

jobs:
  java-sdk-mac:
    # mac job for java sdk. steps are almost same with job 'java-sdk'
    # except mvn deploy won't target all modules, just hybridse-native & openmldb-native
    # the job only run on tag push or manual workflow dispatch due to no test runs
    runs-on: macos-11
    env:
      SQL_JAVASDK_ENABLE: ON
      OPENMLDB_BUILD_TARGET: "cp_native_so openmldb"
      NPROC: 3
    steps:
      - uses: actions/checkout@v3

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('java/**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Cache thirdparty
        uses: actions/cache@v3
        with:
          path: |
            .deps/
            thirdsrc
          key: ${{ runner.os }}-thirdparty-${{ hashFiles('third-party/**/CMakeLists.txt', 'third-party/**/*.cmake', 'third-party/**/*.sh') }}

      - name: prepare release
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          VERSION=${VERSION#v}
          VARIANT_TYPE=macos ./java/prepare_release.sh "$VERSION"

      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "8"
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_TOKEN
          gpg-passphrase: GPG_PASSPHRASE # env variable for GPG private key passphrase

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: build jsdk
        run: |
          make build

      - name: mvn deploy
        working-directory: java
        run: |
          # by convention only native submodule has variant release
          # so it is a bit tricky to compile and deploy that
          # firstly run `maven install` install things locally
          # then selectly `mvn deploy` for hybridse-native & openmldb-native
          ./mvnw --batch-mode clean install -DskipTests=true -Dscalatest.skip=true -Dgpg.skip
          # ./mvnw --batch-mode -pl hybridse-native,openmldb-native deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: download shared libraries
        uses: actions/download-artifact@v2
        with:
          name: shared-library-${{ github.sha }}
          path: java
