name: test-macos

on:
  pull_request:
  workflow_dispatch:

jobs:
  macos-build:
    name: Build in MacOS
    runs-on: macos-latest
    env:
      OS: darwin
      ARCH: x86_64
    steps:
      - uses: actions/checkout@v2
      - name: show xcode
        run: |
          ls /Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
          
